### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by InteXX** [melenaos/FileSystemSafeWatcher#1]
There appears to be a bug in the (rather complex) logic statement found at [LIne 66](https://github.com/melenaos/FileSystemSafeWatcher/blob/7048eb60a3830ccb7ff73bf7e8f8690ea478caa3/FileSystemSafeWatcher.cs#L66). [Line 68](https://github.com/melenaos/FileSystemSafeWatcher/blob/7048eb60a3830ccb7ff73bf7e8f8690ea478caa3/FileSystemSafeWatcher.cs#L68) contains a single `&`. Should this not be a double?

**Comment by melenaos** [comment]
You are right, I haven't noticed it.

It's not actually a bug because a&b == a&&b for boolean variables.

But I will fix that to fix the harmony on that.

**Comment by InteXX** [comment]
Gotcha. It popped up for me because I converted it to VB.

Any hint about what the not-implemented `WaitForChanged` overloads are for?

**Comment by melenaos** [comment]
`WaitForChanged` Could be used when you do something and you wait for a filechange to occur.

Instead of getting the changed event from a `Event` you can just use this function to wait for some milliseconds and get the event.

Unfortunately i haven't implemented it yet nor i will in the near future. I am working in a completely different field now and I won't use the `FileSystemSafeWatcher` any more.

**Comment by InteXX** [comment]
@melenaos 

That's fine, I was just curious.

Good work on this. I can see you put a lot of thought into it at the time.

**Comment by InteXX** [comment]
@melenaos 

Are you saying you've left programming?

**Comment by melenaos** [comment]
No, I stopped working on fat-clients and start working on the web so no more file-watchers or Serial port readers for my self!

**Comment by InteXX** [comment]
I don't blame you on those serial port readers...

What a pain in the neck  :-)

**Comment by melenaos** [comment]
Yes!! Custom protocols and poorly documentation is not a great way of starting a new project.

**Comment by InteXX** [comment]
...and don't forget Microsoft bugs that they haven't fixed in years!

**Comment by InteXX** [comment]
Anyway, best of luck to you on your switch.

Thanks for all your hard work on this. It's saving me a bunch.

**Comment by melenaos** [comment]
Thanks!
