### ISSUE TITLE
Support of the new Filters parameters

### ISSUE THREAD

**Issue by ericcanadas** [melenaos/FileSystemSafeWatcher#6]
It's possible to add the support of the new Filters parameter which allows to specify multiple extensions...

**Comment by melenaos** [comment]
Can you send a usage example? How would you use it in the original type?

**Comment by melenaos** [comment]
You can use the existing Filter property
```
        /// <summary>
        /// Gets or sets the filter string, used to determine what files are monitored in a directory.
        /// </summary>
        /// <value>The filter string. The default is "*.*" (Watches all files.)</value>
        public string Filter
        {
            get
            {
                return _fileSystemWatcher.Filter;
            }
            set
            {
                _fileSystemWatcher.Filter = value;
            }
        }
```

**Comment by ericcanadas** [comment]
Hi,
I want to monitor multiple file extensions
I see this thread in my search but your good implementation don't have this fonctionnality :
https://stackoverflow.com/questions/6965184/how-to-set-filter-for-filesystemwatcher-for-multiple-file-types#answer-61145821

**Comment by melenaos** [comment]
I see. Have you tried setting all the filters into the `Filter` property?

Try `watcher.Filter = "*.txt;*.csv"`

If that doesn't work I will implement the Filters

Στάλθηκε από Outlook για Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ericcanadas** [comment]
Yes, I tried this but it's not working !

**Comment by melenaos** [comment]
You can get the new version now.
I hope that helps!

**Comment by ericcanadas** [comment]
Great !
It works like a charm ! ;-)
Thanks for the responsiveness !!

**Comment by melenaos** [comment]
Thanks for testing it!
